version: '3.8'

services:
  db:
    image: mysql:8.0
    env_file:
      - api/.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"

  backend:
    build: ./api
    env_file:
      - api/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}

  ai:
    build: ./ai
    ports:
      - "8000:8000"

  frontend:
    build: ./client
    ports:
      - "5173:5173"